INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (1, 'Formal Language Theory', 34, '2022', 'fall', '501');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (2, 'Logic in Computer Science', 0, '2021', 'spring', '513');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (3, 'Combinatorics', 38, '2022', 'fall', '514');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (4, 'Algorithms for Data Science', 1, '2022', 'spring', '518');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (5, 'Combinatorics and Graph Theory', 40, '2022', 'spring', '575');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (6, 'Quantum Information Systems', 40, '2022', 'spring', '590');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (7, 'Algorithmic Fairness and Strategic Behavior', 0, '2023', 'spring', '591');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (8, 'Computation theory', 40, '2022', 'fall', '601');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (9, 'Advanced Algorithms', 40, '2022', 'spring', '611');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (10, 'Logic', 40, '2022', 'spring', '613');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (11, 'Computational Geometry', 1, '2023', 'spring', '617');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (12, 'Optimization for Computer Science', 40, '2022', 'spring', '651');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (13, 'Approximation Algorithms', 40, '2022', 'spring', '690');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (14, 'Foundations Applied Cryptography', 5, '2022', 'spring', '691');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (15, 'Advanced Cryptography', 20, '2023', 'spring', '692');
INSERT INTO `courses` (`id`, `name`, `capacity`, `year`, `semester`, `courseId`) VALUES (16, 'Machine Learning Theory', 40, '2022', 'spring', '693');
